cicd: run precommit in one job

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -90,9 +90,37 @@ jobs:
         with:
           python-version: 3.12
 
-      - uses: pre-commit/action@v3.0.1
+      - id: precommit_tw
+        uses: pre-commit/action@v3.0.1
         with:
-          extra_args: ${{ matrix.cmd }} --all-files
+          extra_args: end-of-file-fixer --all-files
+        continue-on-error: true
+
+      - id: precommit_mle
+        uses: pre-commit/action@v3.0.1
+        with:
+          extra_args: trailing-whitespace --all-files
+        continue-on-error: true
+
+      - id: precommit_eof
+        uses: pre-commit/action@v3.0.1
+        with:
+          extra_args: mixed-line-ending --all-files
+        continue-on-error: true
+
+      - name: Check precommit failures
+        if: ${{ always () }}
+        run: |
+          failed=0
+          for s in precommit_tw precommit_mle precommit_eof; do
+            if [ "${{ step[s].outcome }}" = "failure" ]; then
+              echo "::error title=${s}::${s} failed"
+              failed=1
+            fi
+          done
+          exit $failed
+        shell: bash
+
   docs:
     runs-on: ubuntu-latest
     env:
